const baseURL = 'http://cgkwvegguide.com/';
//const baseURL = 'http://localhost:8080/edsa-vegguide/';
export const DIRECTORYURL = `${baseURL}listings.php`;
export const SUBMIT_CHANGE = `${baseURL}submitChange.php`;
export const UPDATE_LISTING = `${baseURL}updateListing.php`;
export const VIEW_CHANGES = `${baseURL}viewChanges.php`;
export const UPDATE_CHANGE = `${baseURL}updateChange.php`;
export const NEW_LISTING = `${baseURL}newListing.php`;
export const PAGESIZE = 50;